title: "Shashank's Blog"
author: "Shashank Shekhar"
description: "Blog about projects, programming and technology"

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
paginate: 2                  # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Page settings
show_excerpts: false          # show article previews on the home page instead of headlines
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/
mathjax: true                # required for equations

# Theme settings
style: contrast               # choose between "default", "contrast" and "minimal"
dark_theme: false            # enables dark mode

navigation:                  # (optional) site navigation in the header
  - index.html
  - archive.md
  - about.md

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  envelope: "mailto:er.shashank10@gmail.com"
  linkedin: "https://www.linkedin.com/in/shashank-shekhar10/"
  kaggle: "https://www.kaggle.com/stagnos"
  github: "https://github.com/snsten"
  rss: "/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins: 
 - jekyll-feed
